apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-secret-test
  namespace: external-secrets
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: aws-secret-test
    kind: ClusterSecretStore
  target:
    name: nostr-secret-test
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: nostr-key-test
      property: NOSTR_PRIVATE_KEY