apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-bot-test
  labels:
    app: nostr-bot-test
  namespace: argo-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostr-bot-test
  template:
    metadata:
      labels:
        app: nostr-bot-test
    spec:
      containers:
        - image: nostr-bot-test
          name: nostr-bot-test
          ports:
            - containerPort: 3000
              protocol: TCP
          env:  
            - name: NOSTR_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: nostr-secret-test
                  key: token
         
         
         
         
          
            
    