apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-bot
  labels:
    app: nostr-bot
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostr-bot
  template:
    metadata:
      labels:
        app: nostr-bot
    spec:
      containers:
        - image: nostr-bot
          name: nostr-bot
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
          - name: nostr-key
            mountPath: "/secrets/nostr-key"
            readOnly: true   
      volumes:
      - name: nostr-key
        secret:
          secretName: nostr-key
         
         
         
         
         
          # env:  
          #   - name: NOSTR_PRIVATE_KEY
          #     valueFrom:
          #       secretKeyRef:
          #         name: nostr-key
          #         key: key
            
    