apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-bot
  labels:
    app: nostr-bot
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostr-bot
  template:
    metadata:
      labels:
        app: nostr-bot
    spec:
      containers:
        - image: docker.io/stum0/nostr-bot:1
          name: nostr-bot
          ports:
            - containerPort: 8080
              protocol: TCP












