apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-bot
  labels:
    app: nostr-bot
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostr-bot
  template:
    metadata:
      labels:
        app: nostr-bot
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: nostr-key
        - image: nostr-bot
          name: nostr-bot
          ports:
            - containerPort: 3000
              protocol: TCP
    