apiVersion: apps/v1
kind: Deployment
metadata:
  name: nostr-bot
  labels:
    app: nostr-bot
  namespace: nostr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nostr-bot
  template:
    metadata:
      labels:
        app: nostr-bot
    spec:
      containers:
        - image: nostr-bot
          name: nostr-bot
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: NOSTR_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: NOSTR_PRIVATE_KEY
                  key: nostr-key
                  optional: false