apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nostr-key
  namespace: kube-system
spec:
  encryptedData:
    key: AgCVMgGzb8SH+rbtPStJypWHVzsCtMHSBp7qEnDzGJhGy72Gn7hK+/TR4RQ7mvVIo4QJtRkXfpVcgx2wUcPgND86oh+E9MwyEa2Q5bnYfOJSF4MAWTzUmuOTj75RiER4tk/d3McDStt0VsgeC/sGf6cQEAUyfQpHWJWARNr+uUJtibIPgdZAm6S9G8K7H1aTkppBsrhb0n+A10eSuxqAI0Nw8c98RGz+vxiw7ESiimKH2O8K6LTlaKzdlih/MFTPfjHirmGC2AYqzizhvXmGh2KEFl4Rczm2K7wo3qa22/9z6mFLwDVqfI8YEN/lxToLkpQXZS7tTJs4Et8ODf2mjQozZtMBAXQ9E74wrj7TaRf3AoMNOjajbuWqTQCKoXoMW02+AKfs+D54RoCPzBlC0BcL89pvlrT6QjXsblIwLTKQg1kSAhM6FqObD6Hvu8v7aLIBsIdWiewjtgS+3tmPrCI5+YupYZJ6cI6UUaQrse0p/6IkdH7EE0YDyWO5xqf/AYMsy/6gGu2GE5Htg5wN7+z/cAmClM0HEJq27ZUxsdRwCTCszgMead3tmg3qG2fgDbPoxUR+tCxiotn3u9LvWYlwNddKoGHDfo9i2aCbsakuu6qErHqWmsGIKQ6uvVYm3v+OEJnxFwUmf8hFFKeqs9sg/+ejxj7hkCNaEN8m/jBevRvOEuHsjKcYYhFfHjOTJwR1K8NZpGo1PLnv6/jLebLrBnLXmi+228gYPro8pBj8035uzznw56yNDCSYDcqocxg=
  template:
    metadata:
      creationTimestamp: null
      name: nostr-key
      namespace: kube-system

