apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argo-cd
resources:
- deployment.yaml
- secret.yaml
images:
- name: nostr-bot
  newName: stum0/nostr-bot
  newTag: sha-5a74d28
