apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system
resources:
- deployment.yaml
- secret-test.yaml
images:
- name: nostr-bot
  newName: stum0/nostr-bot
  newTag: sha-b729404
