apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nostr-bot.yaml
images:
- name: nostr-bot
  newName: eu.gcr.io/my-project/postgres
  newTag: latest
- digest: sha256:24a0c4b4a4c0eb97a1aabb8e29f18e917d05abfe1b7a7c07857230879ce7d3d3
  name: nostr-bot
  newName: my-registry/my-app



