apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awssm-secret
  namespace: external-secrets
spec:
  refreshInterval: "30m"
  secretStoreRef:
    name: aws-secret
    kind: ClusterSecretStore
  target:
    name: nostr-secret
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: nostr-key
      property: NOSTR_PRIVATE_KEY