apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nostr-bot
  namespace: kube-system
  annotations:
    argocd-image-updater.argoproj.io/image-list: docker.io/stum0/nostr-bot     
spec:
  project: default
  source:
    repoURL: https://github.com/stum0/nostr_tx_bot.git
    targetRevision: HEAD
    path: infra/argocd/application
  destination: 
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      selfHeal: true
      prune: true