server:
  additionalApplications:
    - name: cluster-config
      namespace: kube-system
      project: default
      source:
        repoURL: https://github.com/stum0/nostr_tx_bot.git
        targetRevision: HEAD
        path: infra/argocd/manifests/cluster
        directory:
          recurse: true
      destination:
        namespace: kube-system
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          prune: true
          selfHeal: true