apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nostr-bot-test
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/stum0/nostr_tx_bot.git
    targetRevision: HEAD
    path: infra-fev/argo-dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
      prune: true