apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nostr-bot
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/stum0/nostr_tx_bot.git
    targetRevision: main
    path: infra/argocd/application
  destination: 
    server: https://kubernetes.default.svc
    namespace: argo-cd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true