apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: kube-system
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 41.7.3
    chart: kube-prometheus-stack
destination:
  server: https://kubernetes.default.svc
  namespace: kube-system