name: Create and publish a Docker image

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'infra/**'
      - '.github/**'
      - ".gitignore"
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'infra/**'
      - '.github/**'
      - ".gitignore"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - run: yarn install
    - run: yarn test

  build-and-push-image:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.WORKFLOW_LOGIN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  kustomize:      
      name: 'Kustomize'
      runs-on: ubuntu-latest
      steps:
        - name: 'Checkout'
          uses: actions/checkout@master
        - name: 'Kustomize Build'
          uses: karancode/kustomize-github-action@master
          with:
            kustomize_version: '3.0.0'
            kustomize_build_dir: '.'
            kustomize_comment: true
            kustomize_output_file: "rendered.yaml"
            kustomize_build_options: "--load_restrictor none"
            enable_alpha_plugins: true
          env:
            GITHUB_ACCESS_TOKEN: ${{ secrets.WORKFLOW_LOGIN  }}














    

  # deploy:
  #   name: Deploy
  #   runs-on: ubuntu-latest
  #   needs: build-and-push-image

  #   steps:
  #    - name: Check out code
  #      uses: actions/checkout@v3

  #    - name: Setup Kustomize
  #      uses: imranismail/setup-kustomize@v2
  #      with:
  #       kustomize-version: "3.8.7"

  #    - name: Update Kubernetes resources
  #      env:
  #        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  #      run: |
  #       cd  infra/argocd/manifests/cluster
  #       kustomize edit set image nostr-bot=$DOCKER_USERNAME/nostr-bot:$GITHUB_SHA
  #       cat kustomization.yaml
        
  #    - name: Commit files
  #      run: |
  #       git config --local user.email "action@github.com"
  #       git config --local user.name "GitHub Action"
  #       git commit -am "Bump docker tag"

  #    - name: Push changes
  #      uses: ad-m/github-push-action@master
  #      with:
  #       github_token: ${{ secrets.GITHUB_TOKEN }}   

       